import {
  type IconDefinition,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBoxArchive,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronUp,
  faCircleInfo,
  faCircleQuestion,
  faCompass,
  faCubesStacked,
  faDiagramProject,
  faDisplay,
  faExpand,
  faFeatherPointed,
  faFileArrowDown,
  faFileArrowUp,
  faFileImport,
  faFloppyDisk,
  faFolder,
  faForwardStep,
  faGears,
  faLayerGroup,
  faListCheck,
  faMagnifyingGlass,
  faPen,
  faPenNib,
  faPlus,
  faRocket,
  faRotate,
  faShieldHalved,
  faSliders,
  faStethoscope,
  faStop,
  faTableColumns,
  faTag,
  faTrashCan,
  faWandMagicSparkles,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import {
  faCopy as faRegularCopy,
  faTrashCan as faRegularTrashCan,
} from "@fortawesome/free-regular-svg-icons";

export const studioIcons = {
  arrowDown: faArrowDown,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  arrowUp: faArrowUp,
  boxArchive: faBoxArchive,
  check: faCheck,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  chevronUp: faChevronUp,
  circleInfo: faCircleInfo,
  circleQuestion: faCircleQuestion,
  compass: faCompass,
  copy: faRegularCopy,
  cubesStacked: faCubesStacked,
  diagramProject: faDiagramProject,
  display: faDisplay,
  expand: faExpand,
  featherPointed: faFeatherPointed,
  fileArrowDown: faFileArrowDown,
  fileArrowUp: faFileArrowUp,
  fileImport: faFileImport,
  floppyDisk: faFloppyDisk,
  folder: faFolder,
  forwardStep: faForwardStep,
  gears: faGears,
  layerGroup: faLayerGroup,
  listCheck: faListCheck,
  magnifyingGlass: faMagnifyingGlass,
  pen: faPen,
  penNib: faPenNib,
  plus: faPlus,
  regularTrashCan: faRegularTrashCan,
  rocket: faRocket,
  rotate: faRotate,
  shieldHalved: faShieldHalved,
  sliders: faSliders,
  stethoscope: faStethoscope,
  stop: faStop,
  tableColumns: faTableColumns,
  tag: faTag,
  trashCan: faTrashCan,
  wandMagicSparkles: faWandMagicSparkles,
  xmark: faXmark,
} as const;

export function renderIcon(
  definition: IconDefinition,
  className = "",
): string {
  const [width, height, , , pathData] = definition.icon;
  const paths = Array.isArray(pathData) ? pathData : [pathData];
  const classAttribute = className ? `ui-icon ${className}` : "ui-icon";
  return `<svg class="${classAttribute}" viewBox="0 0 ${width} ${height}" aria-hidden="true" focusable="false" role="img">
    ${paths.map((path) => `<path fill="currentColor" d="${path}"></path>`).join("")}
  </svg>`;
}
